version: '3'
services:

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  api-cart:
    build:
      context: ./cart-service
    environment:
      REDIS_URI: "redis://redis:6379"
    depends_on:
      - redis

  api-article:
    build:
      context: ./article-service
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo

  front-admin:
    build:
      context: ./front-admin

  front-client:
    build:
      context: ./front-user

  ingress:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./.compose/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api-cart
      - api-article
      - front-admin
      - front-client
